### ISSUE TITLE
add main categories of groceries

### ISSUE THREAD

**Issue by rausch-supola** [grocerist/grocerist-app#130]
Category chart in dashboard. Changes will be made in baserow, where first category is main category, second one is subcategory

**Comment by kisram** [comment]
We only talked about the chart, but I'm wondering if they want this structure (main category -> subcategories -> products) for the Grocery Categories page as well, what do you think @rausch-supola ?

**Comment by kisram** [comment]
I think we also talked about linking to the grocery detail page from the chart, so they can see which documents it was mentioned in

**Comment by rausch-supola** [comment]
I don't recall if they wanted the structure also in the Grocery Categories page. We could ask or wait for the data to see if it makes sense

**Comment by kisram** [comment]
Since they answered that they want this strcuture everywhere:

- [ ] adjust Baserow for main category, subcategories structure (from our side)
- [ ] adjust the script(s) in grocerist-data
- [ ] adjust the category chart 
- [ ]  "Category mentions by Decade" chart?
- [ ] adjust Grocery Categories page

**Comment by kisram** [comment]
categories table in Baserow has been filled out, so we can start adjusting everything
