### ISSUE TITLE
main categories in category mentions by decade charts

### ISSUE THREAD

**Issue by kisram** [grocerist/grocerist-app#188]
The difference between main categories and subcategories should be visible in these charts, the question is how:
do we need drilldowns or would it be enough the show the difference in the list, e.g. by making the main categories bold

**Comment by kisram** [comment]
Talked about this in person, we'll show the difference in the list, main categories will be listed first and in bold. Maybe add some info text about the chart

**Comment by kisram** [comment]
needs to be adjusted in make_chartsjson.py, since the sorting happens there

**Comment by rausch-supola** [comment]
The order is correct already: the first 10 categories are main categories which is luckily the first row on big screens. Although, when the screen is minimized, some of the main categories move to the next row. Is this ok?
Since the symbols are mixed up now and for distinguishing purposes I suggest using one symbol for the main categories and one another for the subcategories. What do you think?
Still to do: make the main categories bold

**Comment by rausch-supola** [comment]
The subcategories are now under the main categories for clarity reasons, the main categories are in bold. The main and subcategories are ordered alphabetically. The symbols have not been changed.
