### ISSUE TITLE
neighbourhood > mahalle, person > grocerist?

### ISSUE THREAD

**Issue by rausch-supola** [grocerist/grocerist-app#49]
For readability and standardisation we could change all the neighbourhood terms/files/json dump into mahalles. Would this be an improvement? Because now it has gotten a bit chaotic

Is there a reason why the grocerists turn to persons on the subpage? Could this be simplified as well? Or will there be persons that are no grocerists?

**Comment by csae8092** [comment]
> Is there a reason why the grocerists turn to persons on the subpage? Could this be simplified as well? Or will there be persons that are no grocerists?

yes we might have non grocerists as well

> For readability and standardisation we could change all the neighbourhood terms/files/json dump into mahalles. Would this be an improvement? Because now it has gotten a bit chaotic

I'd rather not change any technically relevant names (like file names, baserow-tables, etc) because this might break a lot of things. having something like "technical name" vs. "verbose name" is also a quite common practice, mainly because technical names like e.g. names of database table often need to follow specific naming conventions, whereas a "verbose name" is specific for "human" audience without any need to take care of naming convention. 

Therefore lets stick with the exising "technical" names and get used to the different "verbose names"
